### ISSUE TITLE
compatibility with ethers 4.0.45/4.0.47

### ISSUE THREAD

**Issue by Rjrunner44** [energywebfoundation/iam-client-lib#105] opened 2021-02-03 16:42 UTC
I added ethers 4.0.47 to my project, and for whatever reason, it caused iam-client-lib to break, which uses ethers 4.0.45. I added 4.0.45 specifically and it's ok. But others who will use iam-client-lib will just add "ethers" and have the issue. I'm not sure if this is a npm issue (don't think so) or if ethers itself made breaking changes between 4.0.45 and 4.0.47 (which I think is the case, and a no-no on them). Just posting here in case others run into this.

**Comment by Rjrunner44** [comment] 2021-02-03 16:42
sorry, was for iam-client-lib 1.1.0

**Comment by kosecki123** [comment] 2021-06-17 05:57
Same issue with `iam-client-lib 2.2.0` and locally installed ethers `5.3.1`,

Minimum reproduction code

package.json
```
{
  "name": "did-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ethers": "^5.3.1",
    "iam-client-lib": "^2.2.0"
  }
}
```

index.mjs
```
import { IAM } from "iam-client-lib";
import { Wallet } from "ethers";

const wallet = Wallet.createRandom();

const iam = new IAM({
  privateKey: wallet.privateKey,
  rpcUrl: "https://volta-rpc.energyweb.org/",
});

const res = await iam.initializeConnection();
```

Throws:
```
Error: Error: invalid signer or provider (argument="signerOrProvider", value={"ready":{},"_lastBlockNumber":-2,"_balances":{},"_events":[],"_pollingInterval":4000,"_emitted":{"block":-2},"_fastQueryDate":1623909003276,"connection":{"url":"https://volta-rpc.energyweb.org/"},"_network":{"chainId":73799,"name":"unknown"},"_fastBlockNumber":12143032,"_fastBlockNumberPromise":{}}, code=INVALID_ARGUMENT, version=contracts/5.3.0)
    at Te.<anonymous> (/home/piotr/did-repro/node_modules/iam-client-lib/dist/iam-client-lib.js:1:208494)
    at Generator.throw (<anonymous>)
    at o (/home/piotr/did-repro/node_modules/iam-client-lib/dist/iam-client-lib.js:1:1688)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by kosecki123** [comment] 2021-06-18 08:57
To put more weight on the issues, this is a **stopper** for any integration with existing API/DAPP that already is using other versions of the ethers library.

**Comment by jrhender** [comment] 2021-06-18 21:12
It seems as though, even though ether v4.0.45 is listed in the package.json of the `ew-did-registry/did-ethr-resolver` source 
( https://github.com/energywebfoundation/ew-did-registry/blob/ffaa81ce1253c03ca7684d32d6bee56b790db19a/packages/did-ethr-resolver/package.json#L33 ) it is not listed in the package.json when installing the package (at least for `iam-client-lib@2.2.0` with `@ew-did-registry/did-ethr-resolver@0.1.0-alpha.0`)
![image](https://user-images.githubusercontent.com/4407464/122616216-324b8e80-d047-11eb-8368-d37d5eec273d.png)

**Comment by jrhender** [comment] 2021-06-18 21:24
I think though, that this maybe have been fixed by this commit a few months ago: https://github.com/energywebfoundation/ew-did-registry/commit/f37cacbf9cf080e58f6bb1498ad0c893792b9dc6 
which added 
When changing the dependencies from @kosecki123 's reproduction code to use latest canary `iam-client-lib` (which uses an updated `ew-did-registry/did-ethr-resolver`), no error is thrown.
package.json:
```
{
  "name": "did-repro",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "ethers": "^5.3.1",
    "iam-client-lib": "3.0.0-alpha.22"
  }
}
```

**Comment by jrhender** [comment] 2021-06-18 22:29
Given above ☝️ (i.e. issue is resolved in alpha/canary `iam-client-lib`) should we close this issue @kosecki123 @JGiter ? Or is more investigation needed in your opinions?

**Comment by Rjrunner44** [comment] 2021-06-18 22:41
I still think there is a versioning error in one of the ew libs, but there also still remains an ethers issue (it appears) also of why a supposedly compatible ethers minor version tick is causing breaking changes.

**Comment by jrhender** [comment] 2021-06-18 22:48
@Rjrunner44 Good point, my current understanding was that there was a legitimate breaking change from ethers v4.0.45 to v4.0.47 so client of ew-did-registry packages do have to use precisely v4.0.45. Efforts are underway to migrate ew-did-registry packages to v5

**Comment by jrhender** [comment] 2021-06-18 22:49
@Rjrunner44 can you clarify what you mean by a "versioning error"?

**Comment by Rjrunner44** [comment] 2021-06-18 22:58
The ethers issue (their breaking minor ver). Your comment 2 up is how I would solve this mess also 👍

**Comment by Rjrunner44** [comment] 2021-06-20 21:36
Ran across this: https://blog.bitsrc.io/understanding-peer-dependencies-in-javascript-dbdb4ab5a7be

I wonder if the ew libs should be declaring peer dependencies in the ethers version it expects? This matches the issue, where an ethers is being pulled in by another dependency but which breaks the ew lib. Just posting if helpful.

**Comment by kosecki123** [comment] 2021-06-21 07:09
I think the proper fix for the issue would be to not pass a Signer/Provider object from `iam-client-lib` to `ew-did-*` libraries because that would always require both libraries to use same/compatible ethers library which may be tricky to sync.

Instead the `ew-did-*` or any lib on that matter should create it's own signer/provider object based on private key and other necessary parameters. By following such a design, each library can use their own versions of the ethers.

So instead of 

`new Operator(this._didSigner, this._registrySetting) `

it should be more like

`new Operator(privateKey, rpcNode, ..., this._registrySetting)`

Also, as mentioned above `ew-did-*`  should have ethers lib in the "dependecies" section.

**Comment by jrhender** [comment] 2021-06-21 22:03
@kosecki123 I think that is a good direction. To add, for metamask and walletConnect, we instantiate the `ethers` signer using a web3Provider, corresponding to https://eips.ethereum.org/EIPS/eip-1193. 
https://github.com/energywebfoundation/iam-client-lib/blob/eb6bfd460673eb105c8a16f82db426952048ebaf/src/iam/iam-base.ts#L247

@knzeng-e @JGiter So I think we could have an `ew-did-registry` `Signer` abstraction that accepts either a `privateKey`+`rpcNode` or an EIP-1193 provider. What do you think of this?

**Comment by jrhender** [comment] 2022-01-20 09:26
We have implemented an `EwSigner` abstraction to provide flexibility in the `ethers` version of clients: https://github.com/energywebfoundation/ew-did-registry/blob/aa359a33b61b8a3c479f25aa833d0f437239ef96/packages/did-ethr-resolver/src/implementations/ewSigner.ts#L13

**Closed by jrhender** 2022-01-20 09:26 UTC
